### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by XRui-Y** [taoqi98/UniFedRec#2]
Hi, when I run the Example.ipynb file, it always reports an error ValueError: Dimension must be 5 but is 4 for 'attention_1/transpose_7' (op: 'Transpose') with input shapes: [?,20,?,20,?], [4]. I don't know what is wrong, can you please guide how to run this project, thanks!

**Comment by taoqi98** [comment]
This is caused by conflicting versions of DL libs. The correct versions of the libs are: (1) tensorflow-gpu == 1.13.0 (2) keras == 2.2.4

**Comment by XRui-Y** [comment]
> This is caused by conflicting versions of DL libs. The correct versions of the libs are: (1) tensorflow-gpu == 1.13.0 (2) keras == 2.2.4
Thanks, I also want to ask must be tensorflow-gpu == 1.13.0 , because of the cuda reason I can't seem to adapt the 1.13.0 version, the minimum can be 1.13.1, there are other ways to solve it?

**Comment by taoqi98** [comment]
You should replace K.batch_dot with other functions in your tf.

**Comment by XRui-Y** [comment]
> .batch_dot

Thanks, I changed it to tf.matmul, no error reported, not sure if it's appropriate

**Comment by XRui-Y** [comment]
> 您应该将 K.batch_dot 替换为 tf.

Hi, I switched to tf.batch_dot and it gives me an error, tf doesn't have a batch_dot

**Comment by taoqi98** [comment]
> > 您应该将 K.batch_dot 替换为 tf.
> 
> Hi, I switched to tf.batch_dot and it gives me an error, tf doesn't have a batch_dot
The suggestion "您应该将 K.batch_dot 替换为 tf.batch_dot" does not seem to have been provided by me, and I am not quite clear about what function can replace K.dot in the version of TensorFlow you are using. You can refer to the official TensorFlow API for accurate information.
